### ISSUE TITLE
Error: [string "?"]:472: error opening file.

### ISSUE THREAD

**Issue by Ratismal** [Rinnegatamante/CHMM#15]
Hi,

I'm trying to run CHMM2 v2.8 on my n3ds, but whenever I open it I get this error:

```
Error: [string "?"]:472: error opening file.
```

I've been searching through [the gbatemp thread](https://gbatemp.net/threads/release-chmm2-custom-home-menu-manager-2.397543/) for similar issues, but am coming up blank. I'm running the .3dsx version. 
Here are some screenshots of my file hierarchy:
Root:
![Root Directory](https://i.gyazo.com/f5d44772de9bceff4a7d7023df8ee06b.png)
3ds/CHMM2:
![3ds/CHMM2](https://i.gyazo.com/ed6443b0592d6dfb80734e71735b0323.png)
I think I've installed everything correctly, but I couldn't find any installation instructions so I'm not entirely sure. I can run version 2.6 perfectly fine, but I'm having issues with using shuffled sets on 2.6 so I'd like to upgrade to 2.8 before trying to figure that out. Any help would be greatly appreciated.

Sincerely,
ratismal

**Comment by Rinnegatamante** [comment]
Do you have any theme with non ASCII characters in the name? If so rename those.

**Comment by Ratismal** [comment]
Nope. It even does this when there are no themes in the folder.

**Comment by Rinnegatamante** [comment]
Here's where your error is located: https://github.com/Rinnegatamante/CHMM2/blob/master/source/themes.lua#L18

CHMM2 cannot access Savedata. Start Nintendo Themes Manager and let it generate themes files. If the error persists, delete the extdata themes files (more info on gbatemp), start nintendo themes manager so that it will regenerate themes files and then use CHMM2.

**Comment by Ratismal** [comment]
Deleting the extdata worked! Thanks for your help!
