### ISSUE TITLE
Chmm2 11.4

### ISSUE THREAD

**Issue by J00ker92** [Rinnegatamante/CHMM#38]
Tried to use with doodlebomb and ninahaxx on 11.4 but is stucks after lunch update is coming ? Or what can i do? Thank you

**Comment by LeChatP** [comment]
+1 same problem

**Comment by Rinnegatamante** [comment]
Update is not coming. At least not from me. I dropped the 3DS scene. So mani shit i received from 3DS users, enough of this. Enjoy your bugged CHMM2, won't never be patched.

**Comment by Davidosky99** [comment]
oh well, I hope someone makes an actual decent 3ds custom theme manager ¯\_ (ツ) _/¯  .
Thanks for your previous work and effort you put into this:)

**Comment by linouxis9** [comment]
"Enjoy your bugged CHMM2, won't never be patched"

Not sure this user deserved that message, no need to be as idiot as the people who called you names.

**Comment by MatMaf** [comment]
"Won't never be patched"

So it WILL be patched?

**Comment by the-god-of-memes** [comment]
Sorry to see you leave. But thank you for your contribution.

**Comment by NachtDrache** [comment]
Along with numerous others, I have enjoyed your work and appreciate the effort you put forth into the 3DS scene. Unfortunately, getting shit from the ignorant comes with the territory. Maybe take a break from the 3DS scene for a few months? Good luck with your other projects though.

**Comment by Margen67** [comment]
*This GitHub issue has been brought to you by adf.ly🐝*

**Comment by pbanj** [comment]
"won't never be patched."


![image](https://cloud.githubusercontent.com/assets/17306233/25078577/65f0fbd6-2302-11e7-8d7e-2907dd86cd4e.png))

**Comment by pbanj** [comment]
joking aside this attitude is the exact reason the 3ds scene gave you shit

**Comment by the4anoni** [comment]
Just use cia version ,it works ok

**Comment by SerraraFluttershy** [comment]
Time for someone to fork this and take over...

**Comment by Lordmau5** [comment]
@pbanj - The developer doesn't owe you anything. If they want to have a cocky attitude, they're free to have one. 

BTT: It was a good application, thank you for spending your free time on it :) 

Best of luck in the future!

**Comment by Valeri0p** [comment]
Grazie lo stesso...
Fatti rivedere ogni tanto, vedere quella pic mi fa sempre saltare in aria ;)

**Comment by pbanj** [comment]
@Lordmau5 did i ever say they did? oh that's right i didn't but that's for putting words in my mouth. all i was pointing out is why the 3ds scene has reacted the way they have towards rinn. you're right he has every right to act how he wants but he shouldn't be surprised or angered when the community reacts negatively to his shitty attitude. ever hear the saying "if everyone around you is an asshole, you're the asshole"? that applies here, give a shitty attitude get a shitty attitude. 

you want a truly toxic community? look at the ps3 one. those users were so toxic they actually pushed devs out. i banned so many people for that when i moderated ps3hax. I'm always calling for respect for developers, but if they cant show some back they don't deserve it. when you have people reporting an issue and all the dev ever says is that they must be doing something wrong and offers no help it tends to push people away. 

look at reinand, the reason why most people don't like it is because of rei, the dude is a little shithead who likes to start shit. then you look at luma.... aurora, and tux are nice to users, listen to them, and seem to actually give a shit about issues. oh they also don't go around bashing other cfws, the same cant be said for rei. ever wonder why aureinand changed names to luma? because of a little shit fit rei had.

if rinn has the same attitude in the psvita scene as he did/does in the 3ds scene he will soon be leaving that because of "how the users are". all this guy did was submit an issue and rinn responded liek an asshole. all he had to say was i am no longer updating this and have left the 3ds scene. the "Enjoy your bugged CHMM2" wasn't needed. i could see if the guy was talking shit but he wasn't.


also fwiw i give my free time and sleep up to help test shit when it is needed. like you know that fix for ds games on 11.4 for luma? ya instead of going to sleep i stayed up and helped test it so tux could get it fixed for everyone. you remember otpless? i used to test those also, i also tried over and over on my device everyday trying to get it to brick so we could get closer to tracking down the cause, i also fixed a couple peoples systems(optless bricks) for free so the nand dumps and xor pads could be given to the right people so they could try and see what went wrong. you know the site for the luma nightlies? ya that was almost gone as astro's server shit the bed. i spent money out of my pocket to get a new server for him so they could be brought back. guess what? he has no clue i spent money on it because he didn't need to know. i also spend a lot of my time helping users with issues. do i have to do any of that? no i don't, but it's my way of giving back. so you can kindly fuck off with your "they don't owe you anything" bullshit, as i know they don't, nor do i expect anything from them. but I'm not going to sit here and be like ya it's ok to act like an asshole to your user base and then get mad when they in turn act like an asshole to you.

**Comment by Rinnegatamante** [comment]
1) I'm rude with others same as the others are rude with me. Take a look if i ever made rude responses with polite PSVITA users :) Releasing something and getting 10 pages of shit on GBAtemp is the motivation why i don't owe a fuck anymore to 3DS users.

2) "joking aside this attitude is the exact reason the 3ds scene gave you shit" I'm not the first who acted like this, that attacked me cause some retarded that always flamed in the scene with cell8 and other devs that now is in jail for 20 years cause pedophilia started giving me shit cause adf.ly (were i also was already providing an alternative through donations, but 3ds users just want piracy, infact when i switched to Vita i got as many donations to keep my website adfree at least for 3 years.).

3) Margen67 enjoy block, i have no time to give a fuck to you 12 years old retarded idiot.

4) Stay in topic if you want to discuss the issue if someone will ever fork this project. That's why i leaved this open. This is not gbashittemp, if you just have to flame, troll, OT, go to that piece of shit of forum and enjoy your spam.

5) "won't never be patched" jokes: Sorry if i'm not italian and sometimes i get confused from differences from ways to say different from Italian. Here in Italy a double negation is a negation, not the countrary as in English.

**Comment by flareman** [comment]
As a 3DS CFW user who has never given anyone flak anyplace on the Internet, I think your attitude is insulting to the wrong people, to say the least. It's your right to stop developing your project, even citing zero reasons. Retorts like "enjoy your bugged software" are needless, and people who never were aggressive to you don't deserve them.

Now, on an on-topic note, if you indeed have bugs in your code you are aware of, at the very least you should point them out for other coders to fix, if not you yourself. Sad to see you go, here's to wishing someone else takes over the project.

**Comment by Rinnegatamante** [comment]
"Stay in topic if you want to discuss the issue if someone will ever fork this project. That's why i left this opened. This is not gbashittemp, if you just have to flame, troll, OT, go to that piece of shit of forum and enjoy your spam."

I don't need some 3DS user comments about the drama. Go doing your dramas on GBAtemp. People who really know who i am and how i work already know why i'm now rude with the whole scene and i don't give a fuck anymore in helping people (yes cause before getting shitted i always helped people as can be seen on first 50-60 pages of CHMM2 topic on GBAtemp for example).

The next comment not COMPLETELY related to the topic will cause a massive posts purge and a block of this issue.
(And i'm sure this will happen cause i already know how childish the standard 3ds users are.)

**Comment by flareman** [comment]
Wonderful attitude, bravo on insulting strangers. You know, acting indecently and then threatening to purge the thread does not validate your actions. Ah, well, score one for online dictatorship, I guess.

Continuing on-topic again, I urge you again to at least leave a list of known-to-you bugs for the next owner to fix, if not fix them yourself. It's extremely unprofessional to leave known bugs in the code when abandoning a project - and that's coming from a fellow coder.

Best of luck in your future endeavors.

**Comment by Rinnegatamante** [comment]
"Stay in topic if you want to discuss the issue if someone will ever fork this project. That's why i left this opened. This is not gbashittemp, if you just have to flame, troll, OT, go to that piece of shit of forum and enjoy your spam."

I don't need some 3DS user comments about the drama. Go doing your dramas on GBAtemp. People who really know who i am and how i work already know why i'm now rude with the whole scene and i don't give a fuck anymore in helping people (yes cause before getting shitted i always helped people as can be seen on first 50-60 pages of CHMM2 topic on GBAtemp for example).

The next comment not COMPLETELY related to the topic will cause a massive posts purge and a block of this issue.
(And i'm sure this will happen cause i already know how childish the standard 3ds users are.)


**And this required 13 minutes to be confirmed, you never suprise me 3ds users, cya**

**Comment by asiekierka** [comment]
@Rinnegatamante Looking at the Nintendo homebrew scene through the lens of GBATemp is like looking at the movie critic scene through the lens of YouTube comments.

Unloading the negativity given to you by negative people onto innocent people is how negativity spreads.

Sharing the hatred of others is how communities become hateful.

**Comment by ackwell** [comment]
Restating what was deleted - it would be nice if you could write up a list of bugs you are aware of so that future potential maintainers may be able to look into resolving them.

There are people out there that appreciate the work that's been done, and would like to see it continued.

**Comment by MarcuzD** [comment]
(I never thought I'd be trying to help an issue which Margen67 posted in the chat)

@J00ker92 are you sure it's CHMM's fault? I heard that 11.4 broke *hax very much. Are you on old3DS or new3DS? I heard that *hax doesn't work on old3DS on 11.4 at this point in time. If you have a new3DS then are you using a CFW? If yes which one?

**Comment by Davidosky99** [comment]
And you deleted everything gg lol
